### ISSUE TITLE
Why dose the results significantly different between CPT and DAS.

### ISSUE THREAD

**Issue by A11en0** [UIC-Liu-Lab/CPT#2]
As the title mentioned, the result from your two papers is significantly different, just like RoBERTa on Restaurant dataset, while DAS get 79.81 scores on MF1, and the CPT just only 50.61. Could you tell me why or if I make misunderstood the task setting? Thanks!

CPT:
![image](https://user-images.githubusercontent.com/33925232/218304933-d3f43ba3-f2d9-4ba8-ad7a-a8a17b15ffdc.png)

DAS:
![image](https://user-images.githubusercontent.com/33925232/218304947-9515a0a5-2abc-4797-8e7e-25186b7ce738.png)

**Comment by linhaowei1** [comment]
Hello, Allen! Thanks for your question.
In CPT paper, we conduct experiments using **few-shot** learning end-tasks. While in DAS paper, we use the full dataset. That's why the results in CPT paper are significantly lower than those in DAS paper. You can check our CPT paper for the details of the few-shot learning setting.

**Comment by linhaowei1** [comment]
Hope the comments above will address your problem. 
Let me close this issue. If you have other questions, you can open another issue :)

**Comment by A11en0** [comment]
OK, thanks! I have read the paper of CPT again and find the few-shot setting in the footnote as following picture show.

![image](https://user-images.githubusercontent.com/33925232/218308777-f850ddef-3969-4644-b5f2-8cde857133b3.png)
